workflow:
  rules:
    # Fixes running the CI on "detached" HEAD issue due to using "rules"
    - if: $CI_MERGE_REQUEST_ID
      when: never
    # Default always run
    - when: always

stages:
  - install
  - test
  - build

default:
  interruptible: true

.node_template: &npm_docker
  image: node:16.14.0-slim
  tags: [cloud-dind]

#
# Install
#
install:
  stage: install
  <<: *npm_docker
  script:
    - npm run install:from-lock
#    - npm audit
  artifacts:
    paths:
      - node_modules
    expire_in: 3 hours

#
# Test : Lint & Unit Test
#
test:
  stage: test
  <<: *npm_docker
  script:
    - npm run install:dev-from-lock
    - npm run lint
    - npm run test
  needs: [install]

#
# Build
#
build:
  stage: build
  <<: *npm_docker
  script:
    - npm run build
  rules:
    - if: $CI_COMMIT_REF_PROTECTED == "true" && $CI_COMMIT_REF_SLUG =~ /^(devops|stage|main)$/
      when: on_success
    - when: never
